image: gclayburg/rungroovygitpod:0.1.0-SNAPSHOT

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: "export JAVA_OPTS='-Xmx1024m -XX:TieredStopAtLevel=1 -noverify' && /home/gitpod/springboot/bootrunner.sh --groovyscript.home=/workspace/groovy-dsl-quickstart"
ports:
  - port: 8080
    onOpen: open-preview
